on: push
env:
  NODE_ENV: production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: connect and run
        run: |
          sudo apt install sshpass -y && 
          sshpass -p "${{secrets.SSH_KEY}}" scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r ../test-actions hiweus@ssh-hiweus.alwaysdata.net:/home/hiweus/deploy &&
          sshpass -p "${{secrets.SSH_KEY}}" ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null hiweus@ssh-hiweus.alwaysdata.net sh -c "ls -las ~"
