on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ls -las
      - run: echo "=============================="
      - run: cd .. && ls -las
      - run: ls -las