on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd .. && sshpass -p "${{secrets.SSH_KEY}}" scp -r ../test-actions hiweus@ssh-hiweus.alwaysdata.net:/home/hiweus/deploy
      